### ISSUE TITLE
Job doesn't fail when no version/versionprefix element in csproj was found

### ISSUE THREAD

**Issue by 0nary** [cbcrouse/Versioning.NET#35]
**Describe the bug**
When we use `dotnet-version increment-version-with-git -g "." --branch-name main --author-email actions@github.com`, if there are no tag for the version in any csproj the tool takes 0.0.0 as the current version.

**Expected behavior**
I expected the job to fail.

**Additional context**

https://github.com/0nary/TestCICD/commit/f16818c4b4b1cff5d93b0e2b0452aeee8815ef12

**Comment by cbcrouse** [comment]
@0nary Currently the code does exit when a valid tag is not found.

![image](https://user-images.githubusercontent.com/6248703/197437383-31b8ee9d-1bc4-4423-b9a1-5c5f2165f023.png)

Instead of referring to the tag, I think it may be more correct to say, if the code does not find a version within any of the csproj files, it uses 0.0.0, which I've found to be accurate after reviewing.
